using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
    /// <summary>
    /// Controller class for Info_Verification_Methods
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class InfoVerificationMethodController
    {
        // Preload our schema..
        InfoVerificationMethod thisSchemaLoad = new InfoVerificationMethod();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public InfoVerificationMethodCollection FetchAll()
        {
            InfoVerificationMethodCollection coll = new InfoVerificationMethodCollection();
            Query qry = new Query(InfoVerificationMethod.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoVerificationMethodCollection FetchByID(object InfoVerificationMethodsKey)
        {
            InfoVerificationMethodCollection coll = new InfoVerificationMethodCollection().Where("info_verification_methods_key", InfoVerificationMethodsKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoVerificationMethodCollection FetchByQuery(Query qry)
        {
            InfoVerificationMethodCollection coll = new InfoVerificationMethodCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object InfoVerificationMethodsKey)
        {
            return (InfoVerificationMethod.Delete(InfoVerificationMethodsKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object InfoVerificationMethodsKey)
        {
            return (InfoVerificationMethod.Destroy(InfoVerificationMethodsKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int InfoVerificationMethodsKey,string VerificationName,string VerificationDescription)
	    {
		    InfoVerificationMethod item = new InfoVerificationMethod();
		    
            item.InfoVerificationMethodsKey = InfoVerificationMethodsKey;
            
            item.VerificationName = VerificationName;
            
            item.VerificationDescription = VerificationDescription;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int InfoVerificationMethodsKey,string VerificationName,string VerificationDescription)
	    {
		    InfoVerificationMethod item = new InfoVerificationMethod();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.InfoVerificationMethodsKey = InfoVerificationMethodsKey;
				
			item.VerificationName = VerificationName;
				
			item.VerificationDescription = VerificationDescription;
				
	        item.Save(UserName);
	    }
    }
}
