using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
    /// <summary>
    /// Controller class for Info_Country_List
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class InfoCountryListController
    {
        // Preload our schema..
        InfoCountryList thisSchemaLoad = new InfoCountryList();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public InfoCountryListCollection FetchAll()
        {
            InfoCountryListCollection coll = new InfoCountryListCollection();
            Query qry = new Query(InfoCountryList.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoCountryListCollection FetchByID(object InfoCountryKey)
        {
            InfoCountryListCollection coll = new InfoCountryListCollection().Where("info_country_key", InfoCountryKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoCountryListCollection FetchByQuery(Query qry)
        {
            InfoCountryListCollection coll = new InfoCountryListCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object InfoCountryKey)
        {
            return (InfoCountryList.Delete(InfoCountryKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object InfoCountryKey)
        {
            return (InfoCountryList.Destroy(InfoCountryKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int InfoCountryKey,string CountryValue,string CountryText,string CountryCode,string PhoneCode)
	    {
		    InfoCountryList item = new InfoCountryList();
		    
            item.InfoCountryKey = InfoCountryKey;
            
            item.CountryValue = CountryValue;
            
            item.CountryText = CountryText;
            
            item.CountryCode = CountryCode;
            
            item.PhoneCode = PhoneCode;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int InfoCountryKey,string CountryValue,string CountryText,string CountryCode,string PhoneCode)
	    {
		    InfoCountryList item = new InfoCountryList();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.InfoCountryKey = InfoCountryKey;
				
			item.CountryValue = CountryValue;
				
			item.CountryText = CountryText;
				
			item.CountryCode = CountryCode;
				
			item.PhoneCode = PhoneCode;
				
	        item.Save(UserName);
	    }
    }
}
