using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
    /// <summary>
    /// Controller class for Info_Organizations
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class InfoOrganizationController
    {
        // Preload our schema..
        InfoOrganization thisSchemaLoad = new InfoOrganization();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public InfoOrganizationCollection FetchAll()
        {
            InfoOrganizationCollection coll = new InfoOrganizationCollection();
            Query qry = new Query(InfoOrganization.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoOrganizationCollection FetchByID(object InfoOrganizationsKey)
        {
            InfoOrganizationCollection coll = new InfoOrganizationCollection().Where("info_organizations_key", InfoOrganizationsKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoOrganizationCollection FetchByQuery(Query qry)
        {
            InfoOrganizationCollection coll = new InfoOrganizationCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object InfoOrganizationsKey)
        {
            return (InfoOrganization.Delete(InfoOrganizationsKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object InfoOrganizationsKey)
        {
            return (InfoOrganization.Destroy(InfoOrganizationsKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string OrganizationName,int? UserKeyUpdated,DateTime? LastChanged,string OrganizationDescription,bool? Isbank)
	    {
		    InfoOrganization item = new InfoOrganization();
		    
            item.OrganizationName = OrganizationName;
            
            item.UserKeyUpdated = UserKeyUpdated;
            
            item.LastChanged = LastChanged;
            
            item.OrganizationDescription = OrganizationDescription;
            
            item.Isbank = Isbank;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int InfoOrganizationsKey,string OrganizationName,int? UserKeyUpdated,DateTime? LastChanged,string OrganizationDescription,bool? Isbank)
	    {
		    InfoOrganization item = new InfoOrganization();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.InfoOrganizationsKey = InfoOrganizationsKey;
				
			item.OrganizationName = OrganizationName;
				
			item.UserKeyUpdated = UserKeyUpdated;
				
			item.LastChanged = LastChanged;
				
			item.OrganizationDescription = OrganizationDescription;
				
			item.Isbank = Isbank;
				
	        item.Save(UserName);
	    }
    }
}
