using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
	/// <summary>
	/// Strongly-typed collection for the InfoTimezone class.
	/// </summary>
    [Serializable]
	public partial class InfoTimezoneCollection : ActiveList<InfoTimezone, InfoTimezoneCollection>
	{	   
		public InfoTimezoneCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>InfoTimezoneCollection</returns>
		public InfoTimezoneCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                InfoTimezone o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Info_Timezones table.
	/// </summary>
	[Serializable]
	public partial class InfoTimezone : ActiveRecord<InfoTimezone>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public InfoTimezone()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public InfoTimezone(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public InfoTimezone(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public InfoTimezone(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("Info_Timezones", TableType.Table, DataService.GetInstance("Peerfx"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarInfoTimezoneKey = new TableSchema.TableColumn(schema);
				colvarInfoTimezoneKey.ColumnName = "info_timezone_key";
				colvarInfoTimezoneKey.DataType = DbType.Int32;
				colvarInfoTimezoneKey.MaxLength = 0;
				colvarInfoTimezoneKey.AutoIncrement = true;
				colvarInfoTimezoneKey.IsNullable = false;
				colvarInfoTimezoneKey.IsPrimaryKey = true;
				colvarInfoTimezoneKey.IsForeignKey = false;
				colvarInfoTimezoneKey.IsReadOnly = false;
				colvarInfoTimezoneKey.DefaultSetting = @"";
				colvarInfoTimezoneKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarInfoTimezoneKey);
				
				TableSchema.TableColumn colvarInfoTimezoneName = new TableSchema.TableColumn(schema);
				colvarInfoTimezoneName.ColumnName = "info_timezone_name";
				colvarInfoTimezoneName.DataType = DbType.AnsiString;
				colvarInfoTimezoneName.MaxLength = 200;
				colvarInfoTimezoneName.AutoIncrement = false;
				colvarInfoTimezoneName.IsNullable = true;
				colvarInfoTimezoneName.IsPrimaryKey = false;
				colvarInfoTimezoneName.IsForeignKey = false;
				colvarInfoTimezoneName.IsReadOnly = false;
				colvarInfoTimezoneName.DefaultSetting = @"";
				colvarInfoTimezoneName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarInfoTimezoneName);
				
				TableSchema.TableColumn colvarInfoTimezoneId = new TableSchema.TableColumn(schema);
				colvarInfoTimezoneId.ColumnName = "info_timezone_id";
				colvarInfoTimezoneId.DataType = DbType.AnsiString;
				colvarInfoTimezoneId.MaxLength = 50;
				colvarInfoTimezoneId.AutoIncrement = false;
				colvarInfoTimezoneId.IsNullable = true;
				colvarInfoTimezoneId.IsPrimaryKey = false;
				colvarInfoTimezoneId.IsForeignKey = false;
				colvarInfoTimezoneId.IsReadOnly = false;
				colvarInfoTimezoneId.DefaultSetting = @"";
				colvarInfoTimezoneId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarInfoTimezoneId);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Peerfx"].AddSchema("Info_Timezones",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("InfoTimezoneKey")]
		[Bindable(true)]
		public int InfoTimezoneKey 
		{
			get { return GetColumnValue<int>(Columns.InfoTimezoneKey); }
			set { SetColumnValue(Columns.InfoTimezoneKey, value); }
		}
		  
		[XmlAttribute("InfoTimezoneName")]
		[Bindable(true)]
		public string InfoTimezoneName 
		{
			get { return GetColumnValue<string>(Columns.InfoTimezoneName); }
			set { SetColumnValue(Columns.InfoTimezoneName, value); }
		}
		  
		[XmlAttribute("InfoTimezoneId")]
		[Bindable(true)]
		public string InfoTimezoneId 
		{
			get { return GetColumnValue<string>(Columns.InfoTimezoneId); }
			set { SetColumnValue(Columns.InfoTimezoneId, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varInfoTimezoneName,string varInfoTimezoneId)
		{
			InfoTimezone item = new InfoTimezone();
			
			item.InfoTimezoneName = varInfoTimezoneName;
			
			item.InfoTimezoneId = varInfoTimezoneId;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varInfoTimezoneKey,string varInfoTimezoneName,string varInfoTimezoneId)
		{
			InfoTimezone item = new InfoTimezone();
			
				item.InfoTimezoneKey = varInfoTimezoneKey;
			
				item.InfoTimezoneName = varInfoTimezoneName;
			
				item.InfoTimezoneId = varInfoTimezoneId;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn InfoTimezoneKeyColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn InfoTimezoneNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn InfoTimezoneIdColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string InfoTimezoneKey = @"info_timezone_key";
			 public static string InfoTimezoneName = @"info_timezone_name";
			 public static string InfoTimezoneId = @"info_timezone_id";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
