using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
    /// <summary>
    /// Controller class for Info_Banks
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class InfoBankController
    {
        // Preload our schema..
        InfoBank thisSchemaLoad = new InfoBank();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public InfoBankCollection FetchAll()
        {
            InfoBankCollection coll = new InfoBankCollection();
            Query qry = new Query(InfoBank.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoBankCollection FetchByID(object InfoBankKey)
        {
            InfoBankCollection coll = new InfoBankCollection().Where("info_bank_key", InfoBankKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoBankCollection FetchByQuery(Query qry)
        {
            InfoBankCollection coll = new InfoBankCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object InfoBankKey)
        {
            return (InfoBank.Delete(InfoBankKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object InfoBankKey)
        {
            return (InfoBank.Destroy(InfoBankKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string BankName,int? UserKeyUpdated,DateTime? LastChanged,string BankDescription)
	    {
		    InfoBank item = new InfoBank();
		    
            item.BankName = BankName;
            
            item.UserKeyUpdated = UserKeyUpdated;
            
            item.LastChanged = LastChanged;
            
            item.BankDescription = BankDescription;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int InfoBankKey,string BankName,int? UserKeyUpdated,DateTime? LastChanged,string BankDescription)
	    {
		    InfoBank item = new InfoBank();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.InfoBankKey = InfoBankKey;
				
			item.BankName = BankName;
				
			item.UserKeyUpdated = UserKeyUpdated;
				
			item.LastChanged = LastChanged;
				
			item.BankDescription = BankDescription;
				
	        item.Save(UserName);
	    }
    }
}
