using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
    /// <summary>
    /// Controller class for Info_Phone_Type
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class InfoPhoneTypeController
    {
        // Preload our schema..
        InfoPhoneType thisSchemaLoad = new InfoPhoneType();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public InfoPhoneTypeCollection FetchAll()
        {
            InfoPhoneTypeCollection coll = new InfoPhoneTypeCollection();
            Query qry = new Query(InfoPhoneType.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoPhoneTypeCollection FetchByID(object PhoneTypeKey)
        {
            InfoPhoneTypeCollection coll = new InfoPhoneTypeCollection().Where("Phone_Type_Key", PhoneTypeKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoPhoneTypeCollection FetchByQuery(Query qry)
        {
            InfoPhoneTypeCollection coll = new InfoPhoneTypeCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object PhoneTypeKey)
        {
            return (InfoPhoneType.Delete(PhoneTypeKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object PhoneTypeKey)
        {
            return (InfoPhoneType.Destroy(PhoneTypeKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int PhoneTypeKey,string PhoneTypeText)
	    {
		    InfoPhoneType item = new InfoPhoneType();
		    
            item.PhoneTypeKey = PhoneTypeKey;
            
            item.PhoneTypeText = PhoneTypeText;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int PhoneTypeKey,string PhoneTypeText)
	    {
		    InfoPhoneType item = new InfoPhoneType();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.PhoneTypeKey = PhoneTypeKey;
				
			item.PhoneTypeText = PhoneTypeText;
				
	        item.Save(UserName);
	    }
    }
}
