using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
	/// <summary>
	/// Strongly-typed collection for the InfoOrganization class.
	/// </summary>
    [Serializable]
	public partial class InfoOrganizationCollection : ActiveList<InfoOrganization, InfoOrganizationCollection>
	{	   
		public InfoOrganizationCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>InfoOrganizationCollection</returns>
		public InfoOrganizationCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                InfoOrganization o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Info_Organizations table.
	/// </summary>
	[Serializable]
	public partial class InfoOrganization : ActiveRecord<InfoOrganization>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public InfoOrganization()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public InfoOrganization(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public InfoOrganization(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public InfoOrganization(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("Info_Organizations", TableType.Table, DataService.GetInstance("Peerfx"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarInfoOrganizationsKey = new TableSchema.TableColumn(schema);
				colvarInfoOrganizationsKey.ColumnName = "info_organizations_key";
				colvarInfoOrganizationsKey.DataType = DbType.Int32;
				colvarInfoOrganizationsKey.MaxLength = 0;
				colvarInfoOrganizationsKey.AutoIncrement = true;
				colvarInfoOrganizationsKey.IsNullable = false;
				colvarInfoOrganizationsKey.IsPrimaryKey = true;
				colvarInfoOrganizationsKey.IsForeignKey = false;
				colvarInfoOrganizationsKey.IsReadOnly = false;
				colvarInfoOrganizationsKey.DefaultSetting = @"";
				colvarInfoOrganizationsKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarInfoOrganizationsKey);
				
				TableSchema.TableColumn colvarOrganizationName = new TableSchema.TableColumn(schema);
				colvarOrganizationName.ColumnName = "organization_name";
				colvarOrganizationName.DataType = DbType.String;
				colvarOrganizationName.MaxLength = 50;
				colvarOrganizationName.AutoIncrement = false;
				colvarOrganizationName.IsNullable = false;
				colvarOrganizationName.IsPrimaryKey = false;
				colvarOrganizationName.IsForeignKey = false;
				colvarOrganizationName.IsReadOnly = false;
				colvarOrganizationName.DefaultSetting = @"";
				colvarOrganizationName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarOrganizationName);
				
				TableSchema.TableColumn colvarUserKeyUpdated = new TableSchema.TableColumn(schema);
				colvarUserKeyUpdated.ColumnName = "user_key_updated";
				colvarUserKeyUpdated.DataType = DbType.Int32;
				colvarUserKeyUpdated.MaxLength = 0;
				colvarUserKeyUpdated.AutoIncrement = false;
				colvarUserKeyUpdated.IsNullable = true;
				colvarUserKeyUpdated.IsPrimaryKey = false;
				colvarUserKeyUpdated.IsForeignKey = false;
				colvarUserKeyUpdated.IsReadOnly = false;
				colvarUserKeyUpdated.DefaultSetting = @"";
				colvarUserKeyUpdated.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUserKeyUpdated);
				
				TableSchema.TableColumn colvarLastChanged = new TableSchema.TableColumn(schema);
				colvarLastChanged.ColumnName = "last_changed";
				colvarLastChanged.DataType = DbType.DateTime;
				colvarLastChanged.MaxLength = 0;
				colvarLastChanged.AutoIncrement = false;
				colvarLastChanged.IsNullable = true;
				colvarLastChanged.IsPrimaryKey = false;
				colvarLastChanged.IsForeignKey = false;
				colvarLastChanged.IsReadOnly = false;
				colvarLastChanged.DefaultSetting = @"";
				colvarLastChanged.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLastChanged);
				
				TableSchema.TableColumn colvarOrganizationDescription = new TableSchema.TableColumn(schema);
				colvarOrganizationDescription.ColumnName = "organization_description";
				colvarOrganizationDescription.DataType = DbType.String;
				colvarOrganizationDescription.MaxLength = 50;
				colvarOrganizationDescription.AutoIncrement = false;
				colvarOrganizationDescription.IsNullable = true;
				colvarOrganizationDescription.IsPrimaryKey = false;
				colvarOrganizationDescription.IsForeignKey = false;
				colvarOrganizationDescription.IsReadOnly = false;
				colvarOrganizationDescription.DefaultSetting = @"";
				colvarOrganizationDescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarOrganizationDescription);
				
				TableSchema.TableColumn colvarOrganizationType = new TableSchema.TableColumn(schema);
				colvarOrganizationType.ColumnName = "organization_type";
				colvarOrganizationType.DataType = DbType.Int32;
				colvarOrganizationType.MaxLength = 0;
				colvarOrganizationType.AutoIncrement = false;
				colvarOrganizationType.IsNullable = true;
				colvarOrganizationType.IsPrimaryKey = false;
				colvarOrganizationType.IsForeignKey = false;
				colvarOrganizationType.IsReadOnly = false;
				colvarOrganizationType.DefaultSetting = @"";
				colvarOrganizationType.ForeignKeyTableName = "";
				schema.Columns.Add(colvarOrganizationType);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Peerfx"].AddSchema("Info_Organizations",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("InfoOrganizationsKey")]
		[Bindable(true)]
		public int InfoOrganizationsKey 
		{
			get { return GetColumnValue<int>(Columns.InfoOrganizationsKey); }
			set { SetColumnValue(Columns.InfoOrganizationsKey, value); }
		}
		  
		[XmlAttribute("OrganizationName")]
		[Bindable(true)]
		public string OrganizationName 
		{
			get { return GetColumnValue<string>(Columns.OrganizationName); }
			set { SetColumnValue(Columns.OrganizationName, value); }
		}
		  
		[XmlAttribute("UserKeyUpdated")]
		[Bindable(true)]
		public int? UserKeyUpdated 
		{
			get { return GetColumnValue<int?>(Columns.UserKeyUpdated); }
			set { SetColumnValue(Columns.UserKeyUpdated, value); }
		}
		  
		[XmlAttribute("LastChanged")]
		[Bindable(true)]
		public DateTime? LastChanged 
		{
			get { return GetColumnValue<DateTime?>(Columns.LastChanged); }
			set { SetColumnValue(Columns.LastChanged, value); }
		}
		  
		[XmlAttribute("OrganizationDescription")]
		[Bindable(true)]
		public string OrganizationDescription 
		{
			get { return GetColumnValue<string>(Columns.OrganizationDescription); }
			set { SetColumnValue(Columns.OrganizationDescription, value); }
		}
		  
		[XmlAttribute("OrganizationType")]
		[Bindable(true)]
		public int? OrganizationType 
		{
			get { return GetColumnValue<int?>(Columns.OrganizationType); }
			set { SetColumnValue(Columns.OrganizationType, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varOrganizationName,int? varUserKeyUpdated,DateTime? varLastChanged,string varOrganizationDescription,int? varOrganizationType)
		{
			InfoOrganization item = new InfoOrganization();
			
			item.OrganizationName = varOrganizationName;
			
			item.UserKeyUpdated = varUserKeyUpdated;
			
			item.LastChanged = varLastChanged;
			
			item.OrganizationDescription = varOrganizationDescription;
			
			item.OrganizationType = varOrganizationType;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varInfoOrganizationsKey,string varOrganizationName,int? varUserKeyUpdated,DateTime? varLastChanged,string varOrganizationDescription,int? varOrganizationType)
		{
			InfoOrganization item = new InfoOrganization();
			
				item.InfoOrganizationsKey = varInfoOrganizationsKey;
			
				item.OrganizationName = varOrganizationName;
			
				item.UserKeyUpdated = varUserKeyUpdated;
			
				item.LastChanged = varLastChanged;
			
				item.OrganizationDescription = varOrganizationDescription;
			
				item.OrganizationType = varOrganizationType;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn InfoOrganizationsKeyColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn OrganizationNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn UserKeyUpdatedColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn LastChangedColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn OrganizationDescriptionColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn OrganizationTypeColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string InfoOrganizationsKey = @"info_organizations_key";
			 public static string OrganizationName = @"organization_name";
			 public static string UserKeyUpdated = @"user_key_updated";
			 public static string LastChanged = @"last_changed";
			 public static string OrganizationDescription = @"organization_description";
			 public static string OrganizationType = @"organization_type";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
