using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
    /// <summary>
    /// Controller class for Payment_Object_Types
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class PaymentObjectTypeController
    {
        // Preload our schema..
        PaymentObjectType thisSchemaLoad = new PaymentObjectType();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public PaymentObjectTypeCollection FetchAll()
        {
            PaymentObjectTypeCollection coll = new PaymentObjectTypeCollection();
            Query qry = new Query(PaymentObjectType.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public PaymentObjectTypeCollection FetchByID(object PaymentObjectTypeKey)
        {
            PaymentObjectTypeCollection coll = new PaymentObjectTypeCollection().Where("payment_object_type_key", PaymentObjectTypeKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public PaymentObjectTypeCollection FetchByQuery(Query qry)
        {
            PaymentObjectTypeCollection coll = new PaymentObjectTypeCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object PaymentObjectTypeKey)
        {
            return (PaymentObjectType.Delete(PaymentObjectTypeKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object PaymentObjectTypeKey)
        {
            return (PaymentObjectType.Destroy(PaymentObjectTypeKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int PaymentObjectTypeKey,string PaymentObjectTypeDescription,bool? PaymentObjectTypeIsexternal,bool? PaymentObjectTypeRequiresmanualexport)
	    {
		    PaymentObjectType item = new PaymentObjectType();
		    
            item.PaymentObjectTypeKey = PaymentObjectTypeKey;
            
            item.PaymentObjectTypeDescription = PaymentObjectTypeDescription;
            
            item.PaymentObjectTypeIsexternal = PaymentObjectTypeIsexternal;
            
            item.PaymentObjectTypeRequiresmanualexport = PaymentObjectTypeRequiresmanualexport;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int PaymentObjectTypeKey,string PaymentObjectTypeDescription,bool? PaymentObjectTypeIsexternal,bool? PaymentObjectTypeRequiresmanualexport)
	    {
		    PaymentObjectType item = new PaymentObjectType();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.PaymentObjectTypeKey = PaymentObjectTypeKey;
				
			item.PaymentObjectTypeDescription = PaymentObjectTypeDescription;
				
			item.PaymentObjectTypeIsexternal = PaymentObjectTypeIsexternal;
				
			item.PaymentObjectTypeRequiresmanualexport = PaymentObjectTypeRequiresmanualexport;
				
	        item.Save(UserName);
	    }
    }
}
