using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
	/// <summary>
	/// Strongly-typed collection for the PaymentObjectType class.
	/// </summary>
    [Serializable]
	public partial class PaymentObjectTypeCollection : ActiveList<PaymentObjectType, PaymentObjectTypeCollection>
	{	   
		public PaymentObjectTypeCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>PaymentObjectTypeCollection</returns>
		public PaymentObjectTypeCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                PaymentObjectType o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Payment_Object_Types table.
	/// </summary>
	[Serializable]
	public partial class PaymentObjectType : ActiveRecord<PaymentObjectType>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public PaymentObjectType()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public PaymentObjectType(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public PaymentObjectType(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public PaymentObjectType(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("Payment_Object_Types", TableType.Table, DataService.GetInstance("Peerfx"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarPaymentObjectTypeKey = new TableSchema.TableColumn(schema);
				colvarPaymentObjectTypeKey.ColumnName = "payment_object_type_key";
				colvarPaymentObjectTypeKey.DataType = DbType.Int32;
				colvarPaymentObjectTypeKey.MaxLength = 0;
				colvarPaymentObjectTypeKey.AutoIncrement = false;
				colvarPaymentObjectTypeKey.IsNullable = false;
				colvarPaymentObjectTypeKey.IsPrimaryKey = true;
				colvarPaymentObjectTypeKey.IsForeignKey = false;
				colvarPaymentObjectTypeKey.IsReadOnly = false;
				colvarPaymentObjectTypeKey.DefaultSetting = @"";
				colvarPaymentObjectTypeKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPaymentObjectTypeKey);
				
				TableSchema.TableColumn colvarPaymentObjectTypeDescription = new TableSchema.TableColumn(schema);
				colvarPaymentObjectTypeDescription.ColumnName = "payment_object_type_description";
				colvarPaymentObjectTypeDescription.DataType = DbType.String;
				colvarPaymentObjectTypeDescription.MaxLength = 50;
				colvarPaymentObjectTypeDescription.AutoIncrement = false;
				colvarPaymentObjectTypeDescription.IsNullable = true;
				colvarPaymentObjectTypeDescription.IsPrimaryKey = false;
				colvarPaymentObjectTypeDescription.IsForeignKey = false;
				colvarPaymentObjectTypeDescription.IsReadOnly = false;
				colvarPaymentObjectTypeDescription.DefaultSetting = @"";
				colvarPaymentObjectTypeDescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPaymentObjectTypeDescription);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Peerfx"].AddSchema("Payment_Object_Types",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("PaymentObjectTypeKey")]
		[Bindable(true)]
		public int PaymentObjectTypeKey 
		{
			get { return GetColumnValue<int>(Columns.PaymentObjectTypeKey); }
			set { SetColumnValue(Columns.PaymentObjectTypeKey, value); }
		}
		  
		[XmlAttribute("PaymentObjectTypeDescription")]
		[Bindable(true)]
		public string PaymentObjectTypeDescription 
		{
			get { return GetColumnValue<string>(Columns.PaymentObjectTypeDescription); }
			set { SetColumnValue(Columns.PaymentObjectTypeDescription, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int varPaymentObjectTypeKey,string varPaymentObjectTypeDescription)
		{
			PaymentObjectType item = new PaymentObjectType();
			
			item.PaymentObjectTypeKey = varPaymentObjectTypeKey;
			
			item.PaymentObjectTypeDescription = varPaymentObjectTypeDescription;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varPaymentObjectTypeKey,string varPaymentObjectTypeDescription)
		{
			PaymentObjectType item = new PaymentObjectType();
			
				item.PaymentObjectTypeKey = varPaymentObjectTypeKey;
			
				item.PaymentObjectTypeDescription = varPaymentObjectTypeDescription;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn PaymentObjectTypeKeyColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn PaymentObjectTypeDescriptionColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string PaymentObjectTypeKey = @"payment_object_type_key";
			 public static string PaymentObjectTypeDescription = @"payment_object_type_description";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
