using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
	/// <summary>
	/// Strongly-typed collection for the PaymentObject class.
	/// </summary>
    [Serializable]
	public partial class PaymentObjectCollection : ActiveList<PaymentObject, PaymentObjectCollection>
	{	   
		public PaymentObjectCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>PaymentObjectCollection</returns>
		public PaymentObjectCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                PaymentObject o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Payment_Objects table.
	/// </summary>
	[Serializable]
	public partial class PaymentObject : ActiveRecord<PaymentObject>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public PaymentObject()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public PaymentObject(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public PaymentObject(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public PaymentObject(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("Payment_Objects", TableType.Table, DataService.GetInstance("Peerfx"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarPaymentObjectKey = new TableSchema.TableColumn(schema);
				colvarPaymentObjectKey.ColumnName = "payment_object_key";
				colvarPaymentObjectKey.DataType = DbType.Int64;
				colvarPaymentObjectKey.MaxLength = 0;
				colvarPaymentObjectKey.AutoIncrement = true;
				colvarPaymentObjectKey.IsNullable = false;
				colvarPaymentObjectKey.IsPrimaryKey = true;
				colvarPaymentObjectKey.IsForeignKey = false;
				colvarPaymentObjectKey.IsReadOnly = false;
				colvarPaymentObjectKey.DefaultSetting = @"";
				colvarPaymentObjectKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPaymentObjectKey);
				
				TableSchema.TableColumn colvarPaymentObjectType = new TableSchema.TableColumn(schema);
				colvarPaymentObjectType.ColumnName = "payment_object_type";
				colvarPaymentObjectType.DataType = DbType.Int32;
				colvarPaymentObjectType.MaxLength = 0;
				colvarPaymentObjectType.AutoIncrement = false;
				colvarPaymentObjectType.IsNullable = false;
				colvarPaymentObjectType.IsPrimaryKey = false;
				colvarPaymentObjectType.IsForeignKey = false;
				colvarPaymentObjectType.IsReadOnly = false;
				colvarPaymentObjectType.DefaultSetting = @"";
				colvarPaymentObjectType.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPaymentObjectType);
				
				TableSchema.TableColumn colvarObjectAccountKey = new TableSchema.TableColumn(schema);
				colvarObjectAccountKey.ColumnName = "object_account_key";
				colvarObjectAccountKey.DataType = DbType.Int32;
				colvarObjectAccountKey.MaxLength = 0;
				colvarObjectAccountKey.AutoIncrement = false;
				colvarObjectAccountKey.IsNullable = false;
				colvarObjectAccountKey.IsPrimaryKey = false;
				colvarObjectAccountKey.IsForeignKey = false;
				colvarObjectAccountKey.IsReadOnly = false;
				colvarObjectAccountKey.DefaultSetting = @"";
				colvarObjectAccountKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarObjectAccountKey);
				
				TableSchema.TableColumn colvarDateCreated = new TableSchema.TableColumn(schema);
				colvarDateCreated.ColumnName = "date_created";
				colvarDateCreated.DataType = DbType.DateTime;
				colvarDateCreated.MaxLength = 0;
				colvarDateCreated.AutoIncrement = false;
				colvarDateCreated.IsNullable = false;
				colvarDateCreated.IsPrimaryKey = false;
				colvarDateCreated.IsForeignKey = false;
				colvarDateCreated.IsReadOnly = false;
				colvarDateCreated.DefaultSetting = @"";
				colvarDateCreated.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDateCreated);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Peerfx"].AddSchema("Payment_Objects",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("PaymentObjectKey")]
		[Bindable(true)]
		public long PaymentObjectKey 
		{
			get { return GetColumnValue<long>(Columns.PaymentObjectKey); }
			set { SetColumnValue(Columns.PaymentObjectKey, value); }
		}
		  
		[XmlAttribute("PaymentObjectType")]
		[Bindable(true)]
		public int PaymentObjectType 
		{
			get { return GetColumnValue<int>(Columns.PaymentObjectType); }
			set { SetColumnValue(Columns.PaymentObjectType, value); }
		}
		  
		[XmlAttribute("ObjectAccountKey")]
		[Bindable(true)]
		public int ObjectAccountKey 
		{
			get { return GetColumnValue<int>(Columns.ObjectAccountKey); }
			set { SetColumnValue(Columns.ObjectAccountKey, value); }
		}
		  
		[XmlAttribute("DateCreated")]
		[Bindable(true)]
		public DateTime DateCreated 
		{
			get { return GetColumnValue<DateTime>(Columns.DateCreated); }
			set { SetColumnValue(Columns.DateCreated, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int varPaymentObjectType,int varObjectAccountKey,DateTime varDateCreated)
		{
			PaymentObject item = new PaymentObject();
			
			item.PaymentObjectType = varPaymentObjectType;
			
			item.ObjectAccountKey = varObjectAccountKey;
			
			item.DateCreated = varDateCreated;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(long varPaymentObjectKey,int varPaymentObjectType,int varObjectAccountKey,DateTime varDateCreated)
		{
			PaymentObject item = new PaymentObject();
			
				item.PaymentObjectKey = varPaymentObjectKey;
			
				item.PaymentObjectType = varPaymentObjectType;
			
				item.ObjectAccountKey = varObjectAccountKey;
			
				item.DateCreated = varDateCreated;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn PaymentObjectKeyColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn PaymentObjectTypeColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ObjectAccountKeyColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn DateCreatedColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string PaymentObjectKey = @"payment_object_key";
			 public static string PaymentObjectType = @"payment_object_type";
			 public static string ObjectAccountKey = @"object_account_key";
			 public static string DateCreated = @"date_created";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
