using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
    /// <summary>
    /// Controller class for Scheduled_Task
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ScheduledTaskController
    {
        // Preload our schema..
        ScheduledTask thisSchemaLoad = new ScheduledTask();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ScheduledTaskCollection FetchAll()
        {
            ScheduledTaskCollection coll = new ScheduledTaskCollection();
            Query qry = new Query(ScheduledTask.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ScheduledTaskCollection FetchByID(object ScheduledTaskKey)
        {
            ScheduledTaskCollection coll = new ScheduledTaskCollection().Where("scheduled_task_key", ScheduledTaskKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ScheduledTaskCollection FetchByQuery(Query qry)
        {
            ScheduledTaskCollection coll = new ScheduledTaskCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object ScheduledTaskKey)
        {
            return (ScheduledTask.Delete(ScheduledTaskKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object ScheduledTaskKey)
        {
            return (ScheduledTask.Destroy(ScheduledTaskKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int ScheduledTaskType,DateTime DateChanged)
	    {
		    ScheduledTask item = new ScheduledTask();
		    
            item.ScheduledTaskType = ScheduledTaskType;
            
            item.DateChanged = DateChanged;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int ScheduledTaskKey,int ScheduledTaskType,DateTime DateChanged)
	    {
		    ScheduledTask item = new ScheduledTask();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.ScheduledTaskKey = ScheduledTaskKey;
				
			item.ScheduledTaskType = ScheduledTaskType;
				
			item.DateChanged = DateChanged;
				
	        item.Save(UserName);
	    }
    }
}
