using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
    /// <summary>
    /// Controller class for Scheduled_Task_Types
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ScheduledTaskTypeController
    {
        // Preload our schema..
        ScheduledTaskType thisSchemaLoad = new ScheduledTaskType();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ScheduledTaskTypeCollection FetchAll()
        {
            ScheduledTaskTypeCollection coll = new ScheduledTaskTypeCollection();
            Query qry = new Query(ScheduledTaskType.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ScheduledTaskTypeCollection FetchByID(object ScheduledTaskTypeKey)
        {
            ScheduledTaskTypeCollection coll = new ScheduledTaskTypeCollection().Where("scheduled_task_type_key", ScheduledTaskTypeKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ScheduledTaskTypeCollection FetchByQuery(Query qry)
        {
            ScheduledTaskTypeCollection coll = new ScheduledTaskTypeCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object ScheduledTaskTypeKey)
        {
            return (ScheduledTaskType.Delete(ScheduledTaskTypeKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object ScheduledTaskTypeKey)
        {
            return (ScheduledTaskType.Destroy(ScheduledTaskTypeKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int ScheduledTaskTypeKey,string ScheduledTaskTypeDescription)
	    {
		    ScheduledTaskType item = new ScheduledTaskType();
		    
            item.ScheduledTaskTypeKey = ScheduledTaskTypeKey;
            
            item.ScheduledTaskTypeDescription = ScheduledTaskTypeDescription;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int ScheduledTaskTypeKey,string ScheduledTaskTypeDescription)
	    {
		    ScheduledTaskType item = new ScheduledTaskType();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.ScheduledTaskTypeKey = ScheduledTaskTypeKey;
				
			item.ScheduledTaskTypeDescription = ScheduledTaskTypeDescription;
				
	        item.Save(UserName);
	    }
    }
}
