using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
	/// <summary>
	/// Strongly-typed collection for the UsersBankAccount class.
	/// </summary>
    [Serializable]
	public partial class UsersBankAccountCollection : ActiveList<UsersBankAccount, UsersBankAccountCollection>
	{	   
		public UsersBankAccountCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>UsersBankAccountCollection</returns>
		public UsersBankAccountCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                UsersBankAccount o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Users_Bank_Accounts table.
	/// </summary>
	[Serializable]
	public partial class UsersBankAccount : ActiveRecord<UsersBankAccount>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public UsersBankAccount()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public UsersBankAccount(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public UsersBankAccount(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public UsersBankAccount(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("Users_Bank_Accounts", TableType.Table, DataService.GetInstance("Peerfx"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarUsersBankAccountKey = new TableSchema.TableColumn(schema);
				colvarUsersBankAccountKey.ColumnName = "users_bank_account_key";
				colvarUsersBankAccountKey.DataType = DbType.Int32;
				colvarUsersBankAccountKey.MaxLength = 0;
				colvarUsersBankAccountKey.AutoIncrement = true;
				colvarUsersBankAccountKey.IsNullable = false;
				colvarUsersBankAccountKey.IsPrimaryKey = true;
				colvarUsersBankAccountKey.IsForeignKey = false;
				colvarUsersBankAccountKey.IsReadOnly = false;
				colvarUsersBankAccountKey.DefaultSetting = @"";
				colvarUsersBankAccountKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUsersBankAccountKey);
				
				TableSchema.TableColumn colvarUserKey = new TableSchema.TableColumn(schema);
				colvarUserKey.ColumnName = "user_key";
				colvarUserKey.DataType = DbType.Int32;
				colvarUserKey.MaxLength = 0;
				colvarUserKey.AutoIncrement = false;
				colvarUserKey.IsNullable = false;
				colvarUserKey.IsPrimaryKey = false;
				colvarUserKey.IsForeignKey = false;
				colvarUserKey.IsReadOnly = false;
				colvarUserKey.DefaultSetting = @"";
				colvarUserKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUserKey);
				
				TableSchema.TableColumn colvarCurrencyKey = new TableSchema.TableColumn(schema);
				colvarCurrencyKey.ColumnName = "currency_key";
				colvarCurrencyKey.DataType = DbType.Int32;
				colvarCurrencyKey.MaxLength = 0;
				colvarCurrencyKey.AutoIncrement = false;
				colvarCurrencyKey.IsNullable = false;
				colvarCurrencyKey.IsPrimaryKey = false;
				colvarCurrencyKey.IsForeignKey = false;
				colvarCurrencyKey.IsReadOnly = false;
				colvarCurrencyKey.DefaultSetting = @"";
				colvarCurrencyKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCurrencyKey);
				
				TableSchema.TableColumn colvarBankKey = new TableSchema.TableColumn(schema);
				colvarBankKey.ColumnName = "bank_key";
				colvarBankKey.DataType = DbType.String;
				colvarBankKey.MaxLength = 10;
				colvarBankKey.AutoIncrement = false;
				colvarBankKey.IsNullable = false;
				colvarBankKey.IsPrimaryKey = false;
				colvarBankKey.IsForeignKey = false;
				colvarBankKey.IsReadOnly = false;
				colvarBankKey.DefaultSetting = @"";
				colvarBankKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBankKey);
				
				TableSchema.TableColumn colvarBankAccount = new TableSchema.TableColumn(schema);
				colvarBankAccount.ColumnName = "bank_account";
				colvarBankAccount.DataType = DbType.AnsiString;
				colvarBankAccount.MaxLength = 20;
				colvarBankAccount.AutoIncrement = false;
				colvarBankAccount.IsNullable = false;
				colvarBankAccount.IsPrimaryKey = false;
				colvarBankAccount.IsForeignKey = false;
				colvarBankAccount.IsReadOnly = false;
				colvarBankAccount.DefaultSetting = @"";
				colvarBankAccount.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBankAccount);
				
				TableSchema.TableColumn colvarLastChanged = new TableSchema.TableColumn(schema);
				colvarLastChanged.ColumnName = "last_changed";
				colvarLastChanged.DataType = DbType.DateTime;
				colvarLastChanged.MaxLength = 0;
				colvarLastChanged.AutoIncrement = false;
				colvarLastChanged.IsNullable = false;
				colvarLastChanged.IsPrimaryKey = false;
				colvarLastChanged.IsForeignKey = false;
				colvarLastChanged.IsReadOnly = false;
				colvarLastChanged.DefaultSetting = @"";
				colvarLastChanged.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLastChanged);
				
				TableSchema.TableColumn colvarBankAccountDescription = new TableSchema.TableColumn(schema);
				colvarBankAccountDescription.ColumnName = "bank_account_description";
				colvarBankAccountDescription.DataType = DbType.String;
				colvarBankAccountDescription.MaxLength = 100;
				colvarBankAccountDescription.AutoIncrement = false;
				colvarBankAccountDescription.IsNullable = true;
				colvarBankAccountDescription.IsPrimaryKey = false;
				colvarBankAccountDescription.IsForeignKey = false;
				colvarBankAccountDescription.IsReadOnly = false;
				colvarBankAccountDescription.DefaultSetting = @"";
				colvarBankAccountDescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBankAccountDescription);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Peerfx"].AddSchema("Users_Bank_Accounts",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("UsersBankAccountKey")]
		[Bindable(true)]
		public int UsersBankAccountKey 
		{
			get { return GetColumnValue<int>(Columns.UsersBankAccountKey); }
			set { SetColumnValue(Columns.UsersBankAccountKey, value); }
		}
		  
		[XmlAttribute("UserKey")]
		[Bindable(true)]
		public int UserKey 
		{
			get { return GetColumnValue<int>(Columns.UserKey); }
			set { SetColumnValue(Columns.UserKey, value); }
		}
		  
		[XmlAttribute("CurrencyKey")]
		[Bindable(true)]
		public int CurrencyKey 
		{
			get { return GetColumnValue<int>(Columns.CurrencyKey); }
			set { SetColumnValue(Columns.CurrencyKey, value); }
		}
		  
		[XmlAttribute("BankKey")]
		[Bindable(true)]
		public string BankKey 
		{
			get { return GetColumnValue<string>(Columns.BankKey); }
			set { SetColumnValue(Columns.BankKey, value); }
		}
		  
		[XmlAttribute("BankAccount")]
		[Bindable(true)]
		public string BankAccount 
		{
			get { return GetColumnValue<string>(Columns.BankAccount); }
			set { SetColumnValue(Columns.BankAccount, value); }
		}
		  
		[XmlAttribute("LastChanged")]
		[Bindable(true)]
		public DateTime LastChanged 
		{
			get { return GetColumnValue<DateTime>(Columns.LastChanged); }
			set { SetColumnValue(Columns.LastChanged, value); }
		}
		  
		[XmlAttribute("BankAccountDescription")]
		[Bindable(true)]
		public string BankAccountDescription 
		{
			get { return GetColumnValue<string>(Columns.BankAccountDescription); }
			set { SetColumnValue(Columns.BankAccountDescription, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int varUserKey,int varCurrencyKey,string varBankKey,string varBankAccount,DateTime varLastChanged,string varBankAccountDescription)
		{
			UsersBankAccount item = new UsersBankAccount();
			
			item.UserKey = varUserKey;
			
			item.CurrencyKey = varCurrencyKey;
			
			item.BankKey = varBankKey;
			
			item.BankAccount = varBankAccount;
			
			item.LastChanged = varLastChanged;
			
			item.BankAccountDescription = varBankAccountDescription;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varUsersBankAccountKey,int varUserKey,int varCurrencyKey,string varBankKey,string varBankAccount,DateTime varLastChanged,string varBankAccountDescription)
		{
			UsersBankAccount item = new UsersBankAccount();
			
				item.UsersBankAccountKey = varUsersBankAccountKey;
			
				item.UserKey = varUserKey;
			
				item.CurrencyKey = varCurrencyKey;
			
				item.BankKey = varBankKey;
			
				item.BankAccount = varBankAccount;
			
				item.LastChanged = varLastChanged;
			
				item.BankAccountDescription = varBankAccountDescription;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn UsersBankAccountKeyColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn UserKeyColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn CurrencyKeyColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn BankKeyColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn BankAccountColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn LastChangedColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn BankAccountDescriptionColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string UsersBankAccountKey = @"users_bank_account_key";
			 public static string UserKey = @"user_key";
			 public static string CurrencyKey = @"currency_key";
			 public static string BankKey = @"bank_key";
			 public static string BankAccount = @"bank_account";
			 public static string LastChanged = @"last_changed";
			 public static string BankAccountDescription = @"bank_account_description";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
