using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
    /// <summary>
    /// Controller class for Users_Security_Questions
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class UsersSecurityQuestionController
    {
        // Preload our schema..
        UsersSecurityQuestion thisSchemaLoad = new UsersSecurityQuestion();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public UsersSecurityQuestionCollection FetchAll()
        {
            UsersSecurityQuestionCollection coll = new UsersSecurityQuestionCollection();
            Query qry = new Query(UsersSecurityQuestion.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public UsersSecurityQuestionCollection FetchByID(object UsersSecurityQuestionsKey)
        {
            UsersSecurityQuestionCollection coll = new UsersSecurityQuestionCollection().Where("users_security_questions_key", UsersSecurityQuestionsKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public UsersSecurityQuestionCollection FetchByQuery(Query qry)
        {
            UsersSecurityQuestionCollection coll = new UsersSecurityQuestionCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object UsersSecurityQuestionsKey)
        {
            return (UsersSecurityQuestion.Delete(UsersSecurityQuestionsKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object UsersSecurityQuestionsKey)
        {
            return (UsersSecurityQuestion.Destroy(UsersSecurityQuestionsKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int UserKey,int Question,string Answer,DateTime DateCreated,DateTime LastChanged)
	    {
		    UsersSecurityQuestion item = new UsersSecurityQuestion();
		    
            item.UserKey = UserKey;
            
            item.Question = Question;
            
            item.Answer = Answer;
            
            item.DateCreated = DateCreated;
            
            item.LastChanged = LastChanged;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int UsersSecurityQuestionsKey,int UserKey,int Question,string Answer,DateTime DateCreated,DateTime LastChanged)
	    {
		    UsersSecurityQuestion item = new UsersSecurityQuestion();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.UsersSecurityQuestionsKey = UsersSecurityQuestionsKey;
				
			item.UserKey = UserKey;
				
			item.Question = Question;
				
			item.Answer = Answer;
				
			item.DateCreated = DateCreated;
				
			item.LastChanged = LastChanged;
				
	        item.Save(UserName);
	    }
    }
}
