using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
    /// <summary>
    /// Controller class for Users
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class UserController
    {
        // Preload our schema..
        User thisSchemaLoad = new User();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public UserCollection FetchAll()
        {
            UserCollection coll = new UserCollection();
            Query qry = new Query(User.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public UserCollection FetchByID(object UserKey)
        {
            UserCollection coll = new UserCollection().Where("user_key", UserKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public UserCollection FetchByQuery(Query qry)
        {
            UserCollection coll = new UserCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object UserKey)
        {
            return (User.Delete(UserKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object UserKey)
        {
            return (User.Destroy(UserKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string AccountNumber,string Title,string FirstName,string MiddleName,string LastName,string Dob,int? CountryResidence,string Email,string IpAddress,DateTime LastChanged,DateTime SignedUp,int? UserStatus,bool? Isadmin)
	    {
		    User item = new User();
		    
            item.AccountNumber = AccountNumber;
            
            item.Title = Title;
            
            item.FirstName = FirstName;
            
            item.MiddleName = MiddleName;
            
            item.LastName = LastName;
            
            item.Dob = Dob;
            
            item.CountryResidence = CountryResidence;
            
            item.Email = Email;
            
            item.IpAddress = IpAddress;
            
            item.LastChanged = LastChanged;
            
            item.SignedUp = SignedUp;
            
            item.UserStatus = UserStatus;
            
            item.Isadmin = Isadmin;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int UserKey,string AccountNumber,string Title,string FirstName,string MiddleName,string LastName,string Dob,int? CountryResidence,string Email,string IpAddress,DateTime LastChanged,DateTime SignedUp,int? UserStatus,bool? Isadmin)
	    {
		    User item = new User();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.UserKey = UserKey;
				
			item.AccountNumber = AccountNumber;
				
			item.Title = Title;
				
			item.FirstName = FirstName;
				
			item.MiddleName = MiddleName;
				
			item.LastName = LastName;
				
			item.Dob = Dob;
				
			item.CountryResidence = CountryResidence;
				
			item.Email = Email;
				
			item.IpAddress = IpAddress;
				
			item.LastChanged = LastChanged;
				
			item.SignedUp = SignedUp;
				
			item.UserStatus = UserStatus;
				
			item.Isadmin = Isadmin;
				
	        item.Save(UserName);
	    }
    }
}
