using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
    /// <summary>
    /// Controller class for User_Recipients
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class UserRecipientController
    {
        // Preload our schema..
        UserRecipient thisSchemaLoad = new UserRecipient();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public UserRecipientCollection FetchAll()
        {
            UserRecipientCollection coll = new UserRecipientCollection();
            Query qry = new Query(UserRecipient.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public UserRecipientCollection FetchByID(object UserRecipientsKey)
        {
            UserRecipientCollection coll = new UserRecipientCollection().Where("user_recipients_key", UserRecipientsKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public UserRecipientCollection FetchByQuery(Query qry)
        {
            UserRecipientCollection coll = new UserRecipientCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object UserRecipientsKey)
        {
            return (UserRecipient.Delete(UserRecipientsKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object UserRecipientsKey)
        {
            return (UserRecipient.Destroy(UserRecipientsKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int UserRecipientsKey,int? UserKey,long? PaymentObjectKey)
	    {
		    UserRecipient item = new UserRecipient();
		    
            item.UserRecipientsKey = UserRecipientsKey;
            
            item.UserKey = UserKey;
            
            item.PaymentObjectKey = PaymentObjectKey;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int UserRecipientsKey,int? UserKey,long? PaymentObjectKey)
	    {
		    UserRecipient item = new UserRecipient();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.UserRecipientsKey = UserRecipientsKey;
				
			item.UserKey = UserKey;
				
			item.PaymentObjectKey = PaymentObjectKey;
				
	        item.Save(UserName);
	    }
    }
}
