using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Peerfx_DB
{
    /// <summary>
    /// Controller class for Users_Bank_Accounts
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class UsersBankAccountController
    {
        // Preload our schema..
        UsersBankAccount thisSchemaLoad = new UsersBankAccount();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public UsersBankAccountCollection FetchAll()
        {
            UsersBankAccountCollection coll = new UsersBankAccountCollection();
            Query qry = new Query(UsersBankAccount.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public UsersBankAccountCollection FetchByID(object UsersBankAccountKey)
        {
            UsersBankAccountCollection coll = new UsersBankAccountCollection().Where("users_bank_account_key", UsersBankAccountKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public UsersBankAccountCollection FetchByQuery(Query qry)
        {
            UsersBankAccountCollection coll = new UsersBankAccountCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object UsersBankAccountKey)
        {
            return (UsersBankAccount.Delete(UsersBankAccountKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object UsersBankAccountKey)
        {
            return (UsersBankAccount.Destroy(UsersBankAccountKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int UserKey,int CurrencyKey,string BankKey,string BankAccount,DateTime LastChanged,string BankAccountDescription)
	    {
		    UsersBankAccount item = new UsersBankAccount();
		    
            item.UserKey = UserKey;
            
            item.CurrencyKey = CurrencyKey;
            
            item.BankKey = BankKey;
            
            item.BankAccount = BankAccount;
            
            item.LastChanged = LastChanged;
            
            item.BankAccountDescription = BankAccountDescription;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int UsersBankAccountKey,int UserKey,int CurrencyKey,string BankKey,string BankAccount,DateTime LastChanged,string BankAccountDescription)
	    {
		    UsersBankAccount item = new UsersBankAccount();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.UsersBankAccountKey = UsersBankAccountKey;
				
			item.UserKey = UserKey;
				
			item.CurrencyKey = CurrencyKey;
				
			item.BankKey = BankKey;
				
			item.BankAccount = BankAccount;
				
			item.LastChanged = LastChanged;
				
			item.BankAccountDescription = BankAccountDescription;
				
	        item.Save(UserName);
	    }
    }
}
